const products = [
  {
    id: "p1",
    name: "Nike Air Max 90",
    slug: "nike-air-max-90",
    category: "lifestyle",
    brand: "nike",
    price: 3990000,
    compare_at: 0,
    rating: 5,
    image_url: "/images/Group 14.png",
    is_new: true,
    is_best: true,
    is_sale: false,
    sizes: [39, 40, 41, 42],
  },
  {
    id: "p2",
    name: "adidas Ultraboost Light",
    slug: "adidas-ultraboost-light",
    category: "running",
    brand: "adidas",
    price: 2690000,
    compare_at: 0,
    rating: 4.5,
    image_url: "/images/Group 15.png",
    is_new: true,
    is_best: true,
    is_sale: false,
    sizes: [40, 41, 42, 43],
  },
  {
    id: "p3",
    name: "Puma Velocity Nitro 3",
    slug: "puma-velocity-nitro-3",
    category: "running",
    brand: "puma",
    price: 2961000,
    compare_at: 3290000,
    rating: 4.3,
    image_url: "/images/Group 16.png",
    is_new: true,
    is_best: false,
    is_sale: true,
    sizes: [39, 40, 41],
  },
  {
    id: "p4",
    name: "New Balance 530",
    slug: "new-balance-530",
    category: "lifestyle",
    brand: "new-balance",
    price: 2090000,
    compare_at: 0,
    rating: 4.4,
    image_url: "/images/Group 17.png",
    is_new: true,
    is_best: false,
    is_sale: false,
    sizes: [38, 39, 40, 41],
  },
  {
    id: "p5",
    name: "Asics Gel-Kayano 30",
    slug: "asics-gel-kayano-30",
    category: "running",
    brand: "asics",
    price: 2590000,
    compare_at: 0,
    rating: 4.8,
    image_url: "/images/Group 18.png",
    is_new: true,
    is_best: true,
    is_sale: false,
    sizes: [39, 40, 41, 42],
  },
  {
    id: "p6",
    name: "adidas Stan Smith",
    slug: "adidas-stan-smith",
    category: "lifestyle",
    brand: "adidas",
    price: 2390000,
    compare_at: 0,
    rating: 4.6,
    image_url: "/images/Group 19.png",
    is_new: true,
    is_best: false,
    is_sale: false,
    sizes: [39, 40, 41, 42],
  },
  {
    id: "p7",
    name: "Nike Air Force 1",
    slug: "nike-air-force-1",
    category: "lifestyle",
    brand: "nike",
    price: 2241000,
    compare_at: 2490000,
    rating: 4.4,
    image_url: "/images/Group 20.png",
    is_new: true,
    is_best: true,
    is_sale: true,
    sizes: [39, 40, 41, 42],
  },
  {
    id: "p8",
    name: "Nike Pegasus 41",
    slug: "nike-pegasus-41",
    category: "running",
    brand: "nike",
    price: 1490000,
    compare_at: 0,
    rating: 4.1,
    image_url: "/images/Group 21.png",
    is_new: true,
    is_best: false,
    is_sale: false,
    sizes: [39, 40, 41, 42],
  },
  {
    id: "p9",
    name: "adidas Adizero Aruku",
    slug: "adidas-adizero-aruku",
    category: "running",
    brand: "adidas",
    price: 1860000,
    compare_at: 3100000,
    rating: 5,
    image_url: "/images/Group 1.png",
    is_new: true,
    is_best: true,
    is_sale: true,
    sizes: [40, 41, 42, 43],
  },
  {
    id: "p10",
    name: "Nike Zoom Fly 5",
    slug: "nike-zoom-fly-5",
    category: "running",
    brand: "nike",
    price: 3290000,
    compare_at: 4700000,
    rating: 4.7,
    image_url: "/images/Group 3.png",
    is_new: false,
    is_best: true,
    is_sale: true,
    sizes: [39, 40, 41, 42],
  },
  {
    id: "p11",
    name: "Puma Velocity Nitro 3 Black Lime",
    slug: "puma-velocity-nitro-3-black-lime",
    category: "running",
    brand: "puma",
    price: 2090000,
    compare_at: 2850000,
    rating: 4,
    image_url: "/images/Group 7.png",
    is_new: false,
    is_best: false,
    is_sale: true,
    sizes: [39, 40, 41],
  },
  {
    id: "p12",
    name: "Nike Roshe One",
    slug: "nike-roshe-one",
    category: "lifestyle",
    brand: "nike",
    price: 2450000,
    compare_at: 3790000,
    rating: 4.5,
    image_url: "/images/Group 2.png",
    is_new: false,
    is_best: false,
    is_sale: true,
    sizes: [39, 40, 41, 42],
  },
  {
    id: "p13",
    name: "adidas YEEZY Boost 700",
    slug: "adidas-yeezy-boost-700",
    category: "lifestyle",
    brand: "adidas",
    price: 5250000,
    compare_at: 7500000,
    rating: 4.2,
    image_url: "/images/Group 5.png",
    is_new: false,
    is_best: true,
    is_sale: true,
    sizes: [40, 41, 42, 43],
  },
  {
    id: "p14",
    name: "Converse Chuck Taylor High",
    slug: "converse-chuck-taylor-high",
    category: "lifestyle",
    brand: "converse",
    price: 1490000,
    compare_at: 1950000,
    rating: 4.5,
    image_url: "/images/Group 6.png",
    is_new: false,
    is_best: false,
    is_sale: true,
    sizes: [38, 39, 40, 41],
  },
  {
    id: "p15",
    name: "Puma Astoria",
    slug: "puma-astoria",
    category: "lifestyle",
    brand: "puma",
    price: 1390000,
    compare_at: 1899000,
    rating: 4,
    image_url: "/images/Group 8.png",
    is_new: false,
    is_best: false,
    is_sale: true,
    sizes: [38, 39, 40, 41],
  },
];

module.exports = { products };
